import React from 'react';
import { Page, Toolbar, Button, BottomToolbar, Carousel, CarouselItem} from 'react-onsenui';
import 'onsenui/css/onsenui.css';
import 'onsenui/css/onsen-css-components.css';
import './App.css';



function App() {

  return (
    <div className="App">
     <Page>
       <Toolbar>
         <div className='center'>Monite</div></Toolbar>

         <div> Swoją pierwszą książkę o programowaniu kupiłem jeszcze będąc w podstawówce - był to Turbo Assembler Biblia użytkownika, tak rozpoczęła się moja pasja do programowania. W trakcie studiów podjąłem karierę jako Programista PHP, miała to być krótka przygoda, los jednak miał inny plan. Zostaję jednym z pierwszych zatrudnionych programistów w Naszej Klasie gdzie spędzam ponad 4 lata pomagając rozwijać najpopularniejszy portal społecznościowy. Chęć poznania czegoś nowego, innego a jednocześnie możliwość wykorzystania zdobytej wiedzy kieruje mnie do Kanady gdzie spędzam niecałe 2 lata pracując jako Software Engineer dla korporacji z Toronto. Sposobem na opanowanie technicznego języka stają się meet-upy, na których opowiadam o CleanCode, SOLID czy systemach keszowania danych w aplikacjach webowych. Chęć powiązania pracy z pasją jaką są podróże dała impuls aby poszukać pracy zdalnej. Praca dla agencji interaktywnej w Londynie pozwala zarówno podróżować po świecie (między innymi 4 miesiące w Nowej Zelandii oraz Australii) jak i rozwijać interesujące projekty - głównie start-upy w UK. Wtedy też zapada decyzja, że kolejne stanowisko także musi być zdalne. Od roku pracuję jako Fullstack Developer dla Wikimedia Foundation z San Francisco gdzie rozwijam MediaWiki - projekt na którym oparta jest Wikipedia - wielojęzyczna encyklopedia internetową działająca w oparciu o zasadę otwartej treści. Praca zdalna daje więcej czasu dla siebie, dzięki czemu mogę realizować się jako świeżo upieczony tata oraz wciąż rozwijać nietypowe pasje, tj starty w rajdach samochodowych oraz budowanie od postaw własnego inteligentnego domu. 
         Swoją pierwszą książkę o programowaniu kupiłem jeszcze będąc w podstawówce - był to Turbo Assembler Biblia użytkownika, tak rozpoczęła się moja pasja do programowania. W trakcie studiów podjąłem karierę jako Programista PHP, miała to być krótka przygoda, los jednak miał inny plan. Zostaję jednym z pierwszych zatrudnionych programistów w Naszej Klasie gdzie spędzam ponad 4 lata pomagając rozwijać najpopularniejszy portal społecznościowy. Chęć poznania czegoś nowego, innego a jednocześnie możliwość wykorzystania zdobytej wiedzy kieruje mnie do Kanady gdzie spędzam niecałe 2 lata pracując jako Software Engineer dla korporacji z Toronto. Sposobem na opanowanie technicznego języka stają się meet-upy, na których opowiadam o CleanCode, SOLID czy systemach keszowania danych w aplikacjach webowych. Chęć powiązania pracy z pasją jaką są podróże dała impuls aby poszukać pracy zdalnej. Praca dla agencji interaktywnej w Londynie pozwala zarówno podróżować po świecie (między innymi 4 miesiące w Nowej Zelandii oraz Australii) jak i rozwijać interesujące projekty - głównie start-upy w UK. Wtedy też zapada decyzja, że kolejne stanowisko także musi być zdalne. Od roku pracuję jako Fullstack Developer dla Wikimedia Foundation z San Francisco gdzie rozwijam MediaWiki - projekt na którym oparta jest Wikipedia - wielojęzyczna encyklopedia internetową działająca w oparciu o zasadę otwartej treści. Praca zdalna daje więcej czasu dla siebie, dzięki czemu mogę realizować się jako świeżo upieczony tata oraz wciąż rozwijać nietypowe pasje, tj starty w rajdach samochodowych oraz budowanie od postaw własnego inteligentnego domu. 
         Swoją pierwszą książkę o programowaniu kupiłem jeszcze będąc w podstawówce - był to Turbo Assembler Biblia użytkownika, tak rozpoczęła się moja pasja do programowania. W trakcie studiów podjąłem karierę jako Programista PHP, miała to być krótka przygoda, los jednak miał inny plan. Zostaję jednym z pierwszych zatrudnionych programistów w Naszej Klasie gdzie spędzam ponad 4 lata pomagając rozwijać najpopularniejszy portal społecznościowy. Chęć poznania czegoś nowego, innego a jednocześnie możliwość wykorzystania zdobytej wiedzy kieruje mnie do Kanady gdzie spędzam niecałe 2 lata pracując jako Software Engineer dla korporacji z Toronto. Sposobem na opanowanie technicznego języka stają się meet-upy, na których opowiadam o CleanCode, SOLID czy systemach keszowania danych w aplikacjach webowych. Chęć powiązania pracy z pasją jaką są podróże dała impuls aby poszukać pracy zdalnej. Praca dla agencji interaktywnej w Londynie pozwala zarówno podróżować po świecie (między innymi 4 miesiące w Nowej Zelandii oraz Australii) jak i rozwijać interesujące projekty - głównie start-upy w UK. Wtedy też zapada decyzja, że kolejne stanowisko także musi być zdalne. Od roku pracuję jako Fullstack Developer dla Wikimedia Foundation z San Francisco gdzie rozwijam MediaWiki - projekt na którym oparta jest Wikipedia - wielojęzyczna encyklopedia internetową działająca w oparciu o zasadę otwartej treści. Praca zdalna daje więcej czasu dla siebie, dzięki czemu mogę realizować się jako świeżo upieczony tata oraz wciąż rozwijać nietypowe pasje, tj starty w rajdach samochodowych oraz budowanie od postaw własnego inteligentnego domu. 
         Swoją pierwszą książkę o programowaniu kupiłem jeszcze będąc w podstawówce - był to Turbo Assembler Biblia użytkownika, tak rozpoczęła się moja pasja do programowania. W trakcie studiów podjąłem karierę jako Programista PHP, miała to być krótka przygoda, los jednak miał inny plan. Zostaję jednym z pierwszych zatrudnionych programistów w Naszej Klasie gdzie spędzam ponad 4 lata pomagając rozwijać najpopularniejszy portal społecznościowy. Chęć poznania czegoś nowego, innego a jednocześnie możliwość wykorzystania zdobytej wiedzy kieruje mnie do Kanady gdzie spędzam niecałe 2 lata pracując jako Software Engineer dla korporacji z Toronto. Sposobem na opanowanie technicznego języka stają się meet-upy, na których opowiadam o CleanCode, SOLID czy systemach keszowania danych w aplikacjach webowych. Chęć powiązania pracy z pasją jaką są podróże dała impuls aby poszukać pracy zdalnej. Praca dla agencji interaktywnej w Londynie pozwala zarówno podróżować po świecie (między innymi 4 miesiące w Nowej Zelandii oraz Australii) jak i rozwijać interesujące projekty - głównie start-upy w UK. Wtedy też zapada decyzja, że kolejne stanowisko także musi być zdalne. Od roku pracuję jako Fullstack Developer dla Wikimedia Foundation z San Francisco gdzie rozwijam MediaWiki - projekt na którym oparta jest Wikipedia - wielojęzyczna encyklopedia internetową działająca w oparciu o zasadę otwartej treści. Praca zdalna daje więcej czasu dla siebie, dzięki czemu mogę realizować się jako świeżo upieczony tata oraz wciąż rozwijać nietypowe pasje, tj starty w rajdach samochodowych oraz budowanie od postaw własnego inteligentnego domu. 
         Swoją pierwszą książkę o programowaniu kupiłem jeszcze będąc w podstawówce - był to Turbo Assembler Biblia użytkownika, tak rozpoczęła się moja pasja do programowania. W trakcie studiów podjąłem karierę jako Programista PHP, miała to być krótka przygoda, los jednak miał inny plan. Zostaję jednym z pierwszych zatrudnionych programistów w Naszej Klasie gdzie spędzam ponad 4 lata pomagając rozwijać najpopularniejszy portal społecznościowy. Chęć poznania czegoś nowego, innego a jednocześnie możliwość wykorzystania zdobytej wiedzy kieruje mnie do Kanady gdzie spędzam niecałe 2 lata pracując jako Software Engineer dla korporacji z Toronto. Sposobem na opanowanie technicznego języka stają się meet-upy, na których opowiadam o CleanCode, SOLID czy systemach keszowania danych w aplikacjach webowych. Chęć powiązania pracy z pasją jaką są podróże dała impuls aby poszukać pracy zdalnej. Praca dla agencji interaktywnej w Londynie pozwala zarówno podróżować po świecie (między innymi 4 miesiące w Nowej Zelandii oraz Australii) jak i rozwijać interesujące projekty - głównie start-upy w UK. Wtedy też zapada decyzja, że kolejne stanowisko także musi być zdalne. Od roku pracuję jako Fullstack Developer dla Wikimedia Foundation z San Francisco gdzie rozwijam MediaWiki - projekt na którym oparta jest Wikipedia - wielojęzyczna encyklopedia internetową działająca w oparciu o zasadę otwartej treści. Praca zdalna daje więcej czasu dla siebie, dzięki czemu mogę realizować się jako świeżo upieczony tata oraz wciąż rozwijać nietypowe pasje, tj starty w rajdach samochodowych oraz budowanie od postaw własnego inteligentnego domu. 
         Swoją pierwszą książkę o programowaniu kupiłem jeszcze będąc w podstawówce - był to Turbo Assembler Biblia użytkownika, tak rozpoczęła się moja pasja do programowania. W trakcie studiów podjąłem karierę jako Programista PHP, miała to być krótka przygoda, los jednak miał inny plan. Zostaję jednym z pierwszych zatrudnionych programistów w Naszej Klasie gdzie spędzam ponad 4 lata pomagając rozwijać najpopularniejszy portal społecznościowy. Chęć poznania czegoś nowego, innego a jednocześnie możliwość wykorzystania zdobytej wiedzy kieruje mnie do Kanady gdzie spędzam niecałe 2 lata pracując jako Software Engineer dla korporacji z Toronto. Sposobem na opanowanie technicznego języka stają się meet-upy, na których opowiadam o CleanCode, SOLID czy systemach keszowania danych w aplikacjach webowych. Chęć powiązania pracy z pasją jaką są podróże dała impuls aby poszukać pracy zdalnej. Praca dla agencji interaktywnej w Londynie pozwala zarówno podróżować po świecie (między innymi 4 miesiące w Nowej Zelandii oraz Australii) jak i rozwijać interesujące projekty - głównie start-upy w UK. Wtedy też zapada decyzja, że kolejne stanowisko także musi być zdalne. Od roku pracuję jako Fullstack Developer dla Wikimedia Foundation z San Francisco gdzie rozwijam MediaWiki - projekt na którym oparta jest Wikipedia - wielojęzyczna encyklopedia internetową działająca w oparciu o zasadę otwartej treści. Praca zdalna daje więcej czasu dla siebie, dzięki czemu mogę realizować się jako świeżo upieczony tata oraz wciąż rozwijać nietypowe pasje, tj starty w rajdach samochodowych oraz budowanie od postaw własnego inteligentnego domu. 
         Swoją pierwszą książkę o programowaniu kupiłem jeszcze będąc w podstawówce - był to Turbo Assembler Biblia użytkownika, tak rozpoczęła się moja pasja do programowania. W trakcie studiów podjąłem karierę jako Programista PHP, miała to być krótka przygoda, los jednak miał inny plan. Zostaję jednym z pierwszych zatrudnionych programistów w Naszej Klasie gdzie spędzam ponad 4 lata pomagając rozwijać najpopularniejszy portal społecznościowy. Chęć poznania czegoś nowego, innego a jednocześnie możliwość wykorzystania zdobytej wiedzy kieruje mnie do Kanady gdzie spędzam niecałe 2 lata pracując jako Software Engineer dla korporacji z Toronto. Sposobem na opanowanie technicznego języka stają się meet-upy, na których opowiadam o CleanCode, SOLID czy systemach keszowania danych w aplikacjach webowych. Chęć powiązania pracy z pasją jaką są podróże dała impuls aby poszukać pracy zdalnej. Praca dla agencji interaktywnej w Londynie pozwala zarówno podróżować po świecie (między innymi 4 miesiące w Nowej Zelandii oraz Australii) jak i rozwijać interesujące projekty - głównie start-upy w UK. Wtedy też zapada decyzja, że kolejne stanowisko także musi być zdalne. Od roku pracuję jako Fullstack Developer dla Wikimedia Foundation z San Francisco gdzie rozwijam MediaWiki - projekt na którym oparta jest Wikipedia - wielojęzyczna encyklopedia internetową działająca w oparciu o zasadę otwartej treści. Praca zdalna daje więcej czasu dla siebie, dzięki czemu mogę realizować się jako świeżo upieczony tata oraz wciąż rozwijać nietypowe pasje, tj starty w rajdach samochodowych oraz budowanie od postaw własnego inteligentnego domu. 
         Swoją pierwszą książkę o programowaniu kupiłem jeszcze będąc w podstawówce - był to Turbo Assembler Biblia użytkownika, tak rozpoczęła się moja pasja do programowania. W trakcie studiów podjąłem karierę jako Programista PHP, miała to być krótka przygoda, los jednak miał inny plan. Zostaję jednym z pierwszych zatrudnionych programistów w Naszej Klasie gdzie spędzam ponad 4 lata pomagając rozwijać najpopularniejszy portal społecznościowy. Chęć poznania czegoś nowego, innego a jednocześnie możliwość wykorzystania zdobytej wiedzy kieruje mnie do Kanady gdzie spędzam niecałe 2 lata pracując jako Software Engineer dla korporacji z Toronto. Sposobem na opanowanie technicznego języka stają się meet-upy, na których opowiadam o CleanCode, SOLID czy systemach keszowania danych w aplikacjach webowych. Chęć powiązania pracy z pasją jaką są podróże dała impuls aby poszukać pracy zdalnej. Praca dla agencji interaktywnej w Londynie pozwala zarówno podróżować po świecie (między innymi 4 miesiące w Nowej Zelandii oraz Australii) jak i rozwijać interesujące projekty - głównie start-upy w UK. Wtedy też zapada decyzja, że kolejne stanowisko także musi być zdalne. Od roku pracuję jako Fullstack Developer dla Wikimedia Foundation z San Francisco gdzie rozwijam MediaWiki - projekt na którym oparta jest Wikipedia - wielojęzyczna encyklopedia internetową działająca w oparciu o zasadę otwartej treści. Praca zdalna daje więcej czasu dla siebie, dzięki czemu mogę realizować się jako świeżo upieczony tata oraz wciąż rozwijać nietypowe pasje, tj starty w rajdach samochodowych oraz budowanie od postaw własnego inteligentnego domu. 
         Swoją pierwszą książkę o programowaniu kupiłem jeszcze będąc w podstawówce - był to Turbo Assembler Biblia użytkownika, tak rozpoczęła się moja pasja do programowania. W trakcie studiów podjąłem karierę jako Programista PHP, miała to być krótka przygoda, los jednak miał inny plan. Zostaję jednym z pierwszych zatrudnionych programistów w Naszej Klasie gdzie spędzam ponad 4 lata pomagając rozwijać najpopularniejszy portal społecznościowy. Chęć poznania czegoś nowego, innego a jednocześnie możliwość wykorzystania zdobytej wiedzy kieruje mnie do Kanady gdzie spędzam niecałe 2 lata pracując jako Software Engineer dla korporacji z Toronto. Sposobem na opanowanie technicznego języka stają się meet-upy, na których opowiadam o CleanCode, SOLID czy systemach keszowania danych w aplikacjach webowych. Chęć powiązania pracy z pasją jaką są podróże dała impuls aby poszukać pracy zdalnej. Praca dla agencji interaktywnej w Londynie pozwala zarówno podróżować po świecie (między innymi 4 miesiące w Nowej Zelandii oraz Australii) jak i rozwijać interesujące projekty - głównie start-upy w UK. Wtedy też zapada decyzja, że kolejne stanowisko także musi być zdalne. Od roku pracuję jako Fullstack Developer dla Wikimedia Foundation z San Francisco gdzie rozwijam MediaWiki - projekt na którym oparta jest Wikipedia - wielojęzyczna encyklopedia internetową działająca w oparciu o zasadę otwartej treści. Praca zdalna daje więcej czasu dla siebie, dzięki czemu mogę realizować się jako świeżo upieczony tata oraz wciąż rozwijać nietypowe pasje, tj starty w rajdach samochodowych oraz budowanie od postaw własnego inteligentnego domu. 
         Swoją pierwszą książkę o programowaniu kupiłem jeszcze będąc w podstawówce - był to Turbo Assembler Biblia użytkownika, tak rozpoczęła się moja pasja do programowania. W trakcie studiów podjąłem karierę jako Programista PHP, miała to być krótka przygoda, los jednak miał inny plan. Zostaję jednym z pierwszych zatrudnionych programistów w Naszej Klasie gdzie spędzam ponad 4 lata pomagając rozwijać najpopularniejszy portal społecznościowy. Chęć poznania czegoś nowego, innego a jednocześnie możliwość wykorzystania zdobytej wiedzy kieruje mnie do Kanady gdzie spędzam niecałe 2 lata pracując jako Software Engineer dla korporacji z Toronto. Sposobem na opanowanie technicznego języka stają się meet-upy, na których opowiadam o CleanCode, SOLID czy systemach keszowania danych w aplikacjach webowych. Chęć powiązania pracy z pasją jaką są podróże dała impuls aby poszukać pracy zdalnej. Praca dla agencji interaktywnej w Londynie pozwala zarówno podróżować po świecie (między innymi 4 miesiące w Nowej Zelandii oraz Australii) jak i rozwijać interesujące projekty - głównie start-upy w UK. Wtedy też zapada decyzja, że kolejne stanowisko także musi być zdalne. Od roku pracuję jako Fullstack Developer dla Wikimedia Foundation z San Francisco gdzie rozwijam MediaWiki - projekt na którym oparta jest Wikipedia - wielojęzyczna encyklopedia internetową działająca w oparciu o zasadę otwartej treści. Praca zdalna daje więcej czasu dla siebie, dzięki czemu mogę realizować się jako świeżo upieczony tata oraz wciąż rozwijać nietypowe pasje, tj starty w rajdach samochodowych oraz budowanie od postaw własnego inteligentnego domu. 
         Swoją pierwszą książkę o programowaniu kupiłem jeszcze będąc w podstawówce - był to Turbo Assembler Biblia użytkownika, tak rozpoczęła się moja pasja do programowania. W trakcie studiów podjąłem karierę jako Programista PHP, miała to być krótka przygoda, los jednak miał inny plan. Zostaję jednym z pierwszych zatrudnionych programistów w Naszej Klasie gdzie spędzam ponad 4 lata pomagając rozwijać najpopularniejszy portal społecznościowy. Chęć poznania czegoś nowego, innego a jednocześnie możliwość wykorzystania zdobytej wiedzy kieruje mnie do Kanady gdzie spędzam niecałe 2 lata pracując jako Software Engineer dla korporacji z Toronto. Sposobem na opanowanie technicznego języka stają się meet-upy, na których opowiadam o CleanCode, SOLID czy systemach keszowania danych w aplikacjach webowych. Chęć powiązania pracy z pasją jaką są podróże dała impuls aby poszukać pracy zdalnej. Praca dla agencji interaktywnej w Londynie pozwala zarówno podróżować po świecie (między innymi 4 miesiące w Nowej Zelandii oraz Australii) jak i rozwijać interesujące projekty - głównie start-upy w UK. Wtedy też zapada decyzja, że kolejne stanowisko także musi być zdalne. Od roku pracuję jako Fullstack Developer dla Wikimedia Foundation z San Francisco gdzie rozwijam MediaWiki - projekt na którym oparta jest Wikipedia - wielojęzyczna encyklopedia internetową działająca w oparciu o zasadę otwartej treści. Praca zdalna daje więcej czasu dla siebie, dzięki czemu mogę realizować się jako świeżo upieczony tata oraz wciąż rozwijać nietypowe pasje, tj starty w rajdach samochodowych oraz budowanie od postaw własnego inteligentnego domu. 
         Swoją pierwszą książkę o programowaniu kupiłem jeszcze będąc w podstawówce - był to Turbo Assembler Biblia użytkownika, tak rozpoczęła się moja pasja do programowania. W trakcie studiów podjąłem karierę jako Programista PHP, miała to być krótka przygoda, los jednak miał inny plan. Zostaję jednym z pierwszych zatrudnionych programistów w Naszej Klasie gdzie spędzam ponad 4 lata pomagając rozwijać najpopularniejszy portal społecznościowy. Chęć poznania czegoś nowego, innego a jednocześnie możliwość wykorzystania zdobytej wiedzy kieruje mnie do Kanady gdzie spędzam niecałe 2 lata pracując jako Software Engineer dla korporacji z Toronto. Sposobem na opanowanie technicznego języka stają się meet-upy, na których opowiadam o CleanCode, SOLID czy systemach keszowania danych w aplikacjach webowych. Chęć powiązania pracy z pasją jaką są podróże dała impuls aby poszukać pracy zdalnej. Praca dla agencji interaktywnej w Londynie pozwala zarówno podróżować po świecie (między innymi 4 miesiące w Nowej Zelandii oraz Australii) jak i rozwijać interesujące projekty - głównie start-upy w UK. Wtedy też zapada decyzja, że kolejne stanowisko także musi być zdalne. Od roku pracuję jako Fullstack Developer dla Wikimedia Foundation z San Francisco gdzie rozwijam MediaWiki - projekt na którym oparta jest Wikipedia - wielojęzyczna encyklopedia internetową działająca w oparciu o zasadę otwartej treści. Praca zdalna daje więcej czasu dla siebie, dzięki czemu mogę realizować się jako świeżo upieczony tata oraz wciąż rozwijać nietypowe pasje, tj starty w rajdach samochodowych oraz budowanie od postaw własnego inteligentnego domu. 
         Swoją pierwszą książkę o programowaniu kupiłem jeszcze będąc w podstawówce - był to Turbo Assembler Biblia użytkownika, tak rozpoczęła się moja pasja do programowania. W trakcie studiów podjąłem karierę jako Programista PHP, miała to być krótka przygoda, los jednak miał inny plan. Zostaję jednym z pierwszych zatrudnionych programistów w Naszej Klasie gdzie spędzam ponad 4 lata pomagając rozwijać najpopularniejszy portal społecznościowy. Chęć poznania czegoś nowego, innego a jednocześnie możliwość wykorzystania zdobytej wiedzy kieruje mnie do Kanady gdzie spędzam niecałe 2 lata pracując jako Software Engineer dla korporacji z Toronto. Sposobem na opanowanie technicznego języka stają się meet-upy, na których opowiadam o CleanCode, SOLID czy systemach keszowania danych w aplikacjach webowych. Chęć powiązania pracy z pasją jaką są podróże dała impuls aby poszukać pracy zdalnej. Praca dla agencji interaktywnej w Londynie pozwala zarówno podróżować po świecie (między innymi 4 miesiące w Nowej Zelandii oraz Australii) jak i rozwijać interesujące projekty - głównie start-upy w UK. Wtedy też zapada decyzja, że kolejne stanowisko także musi być zdalne. Od roku pracuję jako Fullstack Developer dla Wikimedia Foundation z San Francisco gdzie rozwijam MediaWiki - projekt na którym oparta jest Wikipedia - wielojęzyczna encyklopedia internetową działająca w oparciu o zasadę otwartej treści. Praca zdalna daje więcej czasu dla siebie, dzięki czemu mogę realizować się jako świeżo upieczony tata oraz wciąż rozwijać nietypowe pasje, tj starty w rajdach samochodowych oraz budowanie od postaw własnego inteligentnego domu. 
         </div>
            
            <BottomToolbar className='carouselContainer'>
              <Carousel  fullscreen swipeable itemWidth={1000} animationOptions={"duration: 0.2, delay: 0.4, timing: 'ease-in'"} >
              <CarouselItem swipeable>
                <Button className='center buttons carousel' modifier='outline' >Tap me!</Button>
              <Button className='center buttons carousel' modifier='outline' >Tap me!</Button>
              <Button className='center buttons carousel' modifier='outline' >Tap me!</Button>
              <Button className='center buttons carousel' modifier='outline' >Tap me!</Button>
          
              </CarouselItem>
              

              </Carousel>
            </BottomToolbar>
          </Page>
    </div>
  );
}

export default App;
